import os, sys
import netCDF4 as nc
import numpy as np
import pandas as pd
import random
import matplotlib.pyplot as plt
import time
from ML_additionals import *
from Lower_resolution_ML import low_res_ML
current_directory = os.getcwd()
import logging
from global_ML import global_ml
from dask.distributed import Client, LocalCluster
from dask_jobqueue import SLURMCluster

# initialize logging for later debugging
logging.basicConfig(level=logging.DEBUG, format='%(asctime)s - %(levelname)s - %(message)s')
sys.stdout.reconfigure(line_buffering=True) # print outputs in real time

# debugging
logging.info("--- ML_basis.py script started ---")
print("ML_basis.py started. This text should appear in outputfile", flush=True)

"""
by Atte Laakso / Aalto University

Base structure to initialize development and mapping of different ML models on data 
generated by programs in data_generation and preprocessed with get_data.py

input: spesified below

output (saved to files):
    - feature importance map
    - metadata of the model
    - R2 score map

NOTE: Data cannot currently include NaN values as they will not be handeled. 
Either delete filter them out before using this tool or add missing value handling to this tool
"""

def main():
    # deside if you want to use 10 based logarithm of the target values
    use_log = False

    # tracer file from SALSA (fix)
    fname_tracer = '../SALSA_2010/vbs_sensitivity_base_2010.01_tracer_monmean.nc'

    # deside if you want to use one global model (multimodel=False)
    # or use subdomains and develop model for each (multimodel=True)
    multimodel = False

    # select the ML model to be used 
    # (options: 'RF' for RandomForest, 'DT' for Decisiontrees, 'GB' for gradient boosting 
    #   and 'LR' for linear regression)
    modelsel = 'RF'

    # define the subdomain dimensions
    domain_lat = 1
    domain_lon = 1

    # define output directory
    output_dir = 'FI_results'

    # define the file prefix for test and training datas 
    # if you have no data made, then go create that data using get_data.py and get_data.sh
    # 'dARE_ML_data_250721'
    ML_data = "dARE_ML_data_250721"

    # define settings for Dask, desides if running on local or SLURM cluster
    cluster_config = {
        "type": "local",  # "local" or "slurm"
        "n_workers": 6,
        "threads_per_worker": 1,
        "memory": "11GB",

        # SLURM-specific options (ignored if local)
        "walltime": "00:30:00",
        "queue": "small",
        "job_extra": ["--exclusive", "--account=project_xxxxxx"]
    }

    # use the same random state for all the processes that take that up as parameter
    random_state = 42

    #---------------------------------------------------------------------------------------------------------------------------------------------------
    #---------------------------------------------------------------------------------------------------------------------------------------------------
    # begin computations

    # keep track of time
    start_time = time.time()

    # read data from files (If you want new data, delete the files and go to get_data.py)
    if (os.path.exists(f'{ML_data}_x_train.parquet') and
        os.path.exists(f'{ML_data}_y_train.parquet') and
        os.path.exists(f'{ML_data}_x_test.parquet') and
        os.path.exists(f'{ML_data}_y_test.parquet')):
        
        # data from files
        x_train = pd.read_parquet(f'{ML_data}_x_train.parquet')
        y_train = pd.read_parquet(f'{ML_data}_y_train.parquet')
        x_test = pd.read_parquet(f'{ML_data}_x_test.parquet')
        y_test = pd.read_parquet(f'{ML_data}_y_test.parquet')
        
        # other variables
        with open(f'{ML_data}_metadata.txt', 'r') as f:
            batch_len = int(f.readline().strip())
    else:
        raise ValueError(f"{ML_data}-files not found! Check the name and/or go create the data with get_data.py")

    print(f"Training sets are {len(x_train)}, {len(y_train)} and test sets are {len(x_test)} and {len(y_test)}")
    print(f"Training sets are shaped {x_train.shape}, {y_train.shape} and test sets are {x_test.shape} and {y_test.shape}")

    end_time = time.time()
    # print the duration
    print(f"initialization done. Initializing took {end_time - start_time} seconds")

    # get feature names
    fnames = x_train.columns
    print("Features are ",fnames)

    # read the grid variables from tracer file SALSA
    griddata=nc.Dataset(fname_tracer, 'r', format='NETCDF4_CLASSIC')
    lon=griddata.variables['lon'][:]
    lat=griddata.variables['lat'][:]
    griddata.close()

    # define original shape of the dataset
    original_shape=(len(lat),len(lon))

    # make the outputdir
    output_dir = os.path.join(output_dir, f"data={ML_data}_multimodel={multimodel}_model={modelsel}")
    os.makedirs(output_dir, exist_ok=True)

    if multimodel:
        # calculate ten based logarithms
        if use_log:
            x_train = np.log10(x_train)
            y_train = np.log10(y_train)
            x_test = np.log10(x_test)
            y_test = np.log10(y_test)
        
        # define dask cluster for ml training
        client = initialize_dask_cluster(cluster_config)

        # train and test ML models with domainwise datasets
        low_res_ML(x_train, y_train, x_test, y_test, original_shape, domain_lat, domain_lon, fnames, lon, 
            lat, use_log, random_state, modelsel, output_dir, client)
        
        client.close()

    else:
        # train model on entire dataset using coordinates as features too
        x_train, x_test, fnames = add_coordinates_to_features(lat, lon, x_train, x_test, fnames)
        print("Features are ",fnames)

        # calculate ten based logarithms
        if use_log:
            x_train = np.log10(x_train)
            y_train = np.log10(y_train)
            x_test = np.log10(x_test)
            y_test = np.log10(y_test)
        
        # train and test ML model with all the data
        global_ml(x_train, y_train, x_test, y_test, original_shape, fnames, use_log, 
            output_dir, random_state, modelsel)
    
    return

# function for initilaizing dask cluster for multimodel
def initialize_dask_cluster(config):
    # use slurm
    if config["type"] == "slurm":
        print("Launching SLURMCluster...")
        cluster = SLURMCluster(
            cores=config["threads_per_worker"],
            memory=config["memory"],
            processes=1,
            walltime=config.get("walltime", "01:00:00"),
            queue=config.get("queue", "small"),
            job_extra=config.get("job_extra", []),
        )
        cluster.scale(config["n_workers"])
    # or local
    elif config["type"] == "local":
        print("Launching LocalCluster...")
        cluster = LocalCluster(
            n_workers=config["n_workers"],
            threads_per_worker=config["threads_per_worker"],
            memory_limit=config["memory"]
        )
    else:
        raise ValueError(f"Unknown cluster type: {config['type']}")

    client = Client(cluster)
    print("Dask client started. Dashboard link:", client.dashboard_link)

    # wait for workers to be ready before proceeding
    client.wait_for_workers(n_workers=config["n_workers"])
    print("Dask cluster is ready.")
    
    return client


if __name__ == "__main__":
    main()
